### ISSUE TITLE
Run successful but generate nothing meaningful!

### ISSUE THREAD

**Issue by StackChan** [affinis/SMTa#7]
Hi there, when i use SMTa for microbe analysis in visium data and run SMTa start from spaceranger output
(Human Intestine Cancer (FPPE) data from https://www.10xgenomics.com/datasets/human-intestine-cancer-1-standard)
, i get results as follows,

![image](https://github.com/user-attachments/assets/22676c1f-6923-41f2-b3fc-7e6d1df5050c)

and i run commands
`(base) songkang@dell:/data/pub/SRT/Human_Intestine_Cancer_FFPE$ bash /home/songkang/sc/SMTa/src/microperc.sh -u 1 -i possorted_genome_bam.bam -d /data/pub/tools/nt/nt`
 in cmd terminal,
![image](https://github.com/user-attachments/assets/fee5bdbe-a684-4be4-bed9-9cbf740323fb)

It takes 9h to run it.

Definitely it runs successfully and generate result files "possorted_genome_bam.unmapped.fasta","possorted_genome_bam.merged.microbe.tsv","possorted_genome_bam.merged.tsv","unmapped.nonpolyB.blast.tsv"

but why no  'matrix.mdx' is generated and 'possorted_genome_bam.merged.microbe.tsv' is null and
possorted_genome_bam.taxa.tsv with nothing meaningful,

![image](https://github.com/user-attachments/assets/dac9626a-50e6-4b60-8774-6181a64243f9)

**Comment by affinis** [comment]
10x Visium FFPE is a method designed for targeted mRNA profiling and thus would not capture any other RNAs such as microbial ones, the method uses two probe: polyT and a gene specific probe, the later one ensures capturing targeted mRNA and thus will not provide any chances for non-specific priming, which is the basis of our tool to profile microbial sequences.
So I suggest download 10x public Visium dataset which is not based on a FFPE method for testing our tool, for example, a Fresh Frozen Visium sample. If any other bugs occured, feel free to ask us.

**Comment by StackChan** [comment]
Thank u for ur answering and I get to know about 4 methods of Visium.

1.
So what about this sample,
[fresh-frozen-visium-on-cytassist-human-breast-cancer](https://www.10xgenomics.com/datasets/fresh-frozen-visium-on-cytassist-human-breast-cancer-probe-based-whole-transcriptome-profiling-2-standard)?

It's based platform of visium cytassist and as I' know visium cytassist is also based on gene specific probe.

So only the basic Visium sample works, right?

2.
Also, for Sarge intestine(SI) samples and the given links to download their fastaq files (https://trace.ncbi.nlm.nih.gov/Traces/?view=run_browser&acc=SRR17246775&display=download), I want to know whether it's correct to handle SRR17246775 as follow,

`wget -c https://sra-pub-run-odp.s3.amazonaws.com/sra/SRR17246775/SRR17246775
fasterq-dump -O ./ --split-files -e 10 --include-technical SRR17246775

ll -lah
-rw-rw-r-- 1 songkang songkang  10G Jul 11 18:36 SRR17246775_1.fastq
-rw-rw-r-- 1 songkang songkang  20G Jul 11 18:36 SRR17246775_2.fastq
`

If not, how may I handle it correctly?

**Comment by StackChan** [comment]
And what about https://www.10xgenomics.com/datasets/mouse-kidney-section-coronal-1-standard-1-1-0 and
https://www.10xgenomics.com/datasets/mouse-kidney-section-coronal-1-standard-1-0-0?

**Comment by affinis** [comment]
1. Yes, only the basic Visium sample works, the sample listed here is also not compatible with our pipeline.
2. looks ok.
3. the mouse kidney sample looks ok

**Comment by StackChan** [comment]
Thank u for ur answering and I tried  2& 3. Both of them run spaceranger in your code successfully.

Definitely it runs successfully and generate result files "possorted_genome_bam.unmapped.fasta","possorted_genome_bam.merged.microbe.tsv","possorted_genome_bam.merged.tsv","unmapped.nonpolyB.blast.tsv"
but still no 'matrix.mdx' is generated and 'possorted_genome_bam.merged.microbe.tsv' is null and
possorted_genome_bam.taxa.tsv with nothing meaningful. 

And web_summary.html of 2 is as follows,
![image](https://github.com/user-attachments/assets/e6e7a862-9d1d-431a-a1ee-dacd944af8c2)

You can see there is no error about spaceranger pipeline.

And if sample 2 & 3, or at least 2, is able to detect microbiome signals, I don't know what's wrong with my trail.

**Comment by StackChan** [comment]
Obviously no microbe  signals detected and that's the reason why  still no 'matrix.mdx' is generated and 'possorted_genome_bam.merged.microbe.tsv' is null.

But is there still any error with my samples?

**Comment by StackChan** [comment]
I sincerely hope honored the author to give any possible samples from 10x website to apply SMTa.(or you may also run the mouse kidney samples as I listed above).
I admire your work very much and hope get your precious response.

**Comment by affinis** [comment]
please show me the content of 'unmapped.nonpolyB.blast.tsv', I think there is something wrong with it.

**Comment by affinis** [comment]
In a successfully run, taxids would be found in 'unmapped.nonpolyB.blast.tsv', if not, there may be something wrong with nt database or blastn

**Comment by StackChan** [comment]
`(base) songkang@dell:~/sc/Despot$ head /data/pub/SRT/V1_Mouse_Kidney/unmapped.nonpolyB.blast.tsv
A00984:21:HMKLFDMXX:1:1172:12897:21574|CB:Z:AAACAAGTATCTCCCA-1|UB:Z:ACTGTGTGTTAG        N/A     AK397456.1 Sus scrofa mRNA, clone: SMG010018G10, expressed in submaxillary gland      104      1.98e-41        98.077  87
A00984:21:HMKLFDMXX:1:1172:11704:22482|CB:Z:AAACAAGTATCTCCCA-1|UB:Z:ACTGTGTGTTAG        N/A     AK397456.1 Sus scrofa mRNA, clone: SMG010018G10, expressed in submaxillary gland      104      4.26e-43        99.038  87
A00984:21:HMKLFDMXX:2:1207:31810:3098|CB:Z:AAACAAGTATCTCCCA-1|UB:Z:ACTGTGTGTTAG N/A     NR_046238.1 Rattus norvegicus 5.8S ribosomal RNA (Rn5-8s), ribosomal RNA X00244.1 Rat liver ribosome associated 5.8S rRNA 4W1Z_8 Chain 8, 5.8S ribosomal RNA 4W21_8 Chain 8, 5.8S ribosomal RNA 4W24_8 Chain 8, 5.8S ribosomal RNA 4W26_8 Chain 8, 5.8S ribosomal RNA 6FRK_8 Chain 8, 5.8S ribosomal RNA 3J7O_8 Chain 8, 5.8S ribosomal RNA 3J7Q_8 Chain 8, 5.8S ribosomal RNA 3J92_8 Chain 8, 5.8S rRNA 6LQM_8 Chain 8, 5.8S rRNA 6LSR_8 Chain 8, 5.8S rRNA 6FTG_w Chain w, 5.8S ribosomal RNA 6FTI_w Chain w, 5.8S ribosomal RNA 6FTJ_w Chain w, 5.8S ribosomal RNA 7BHP_L8 Chain L8, 5.8S ribosomal RNA 7A01_h2 Chain h2, 5.8S RIBOSOMAL RNA 6HCF_82 Chain 82, 5.8S ribosomal RNA 6HCJ_81 Chain 81, 5.8S ribosomal RNA 6HCM_82 Chain 82, 5.8S ribosomal RNA 6HCQ_81 Chain 81, 5.8S ribosomal RNA 3J7P_8 Chain 8, 5.8S ribosomal RNA 3J7R_8 Chain 8, 5.8S ribosomal RNA 3JAG_8 Chain 8, 5.8S ribosomal RNA 3JAH_8 Chain 8, 5.8S ribosomal RNA 3JAI_8 Chain 8, 5.8S ribosomal RNA 3JAJ_8 Chain 8, 5.8S ribosomal RNA 3JAN_8 Chain 8, 5.8S ribosomal RNA 5LZS_8 Chain 8, 5.8S ribosomal RNA 5LZT_8 Chain 8, 5.8S ribosomal RNA 5LZU_8 Chain 8, 5.8S ribosomal RNA 5LZV_8 Chain 8, 5.8S ribosomal RNA 5LZW_8 Chain 8, 5.8S ribosomal RNA 5LZX_8 Chain 8, 5.8S ribosomal RNA 5LZY_8 Chain 8, 5.8S ribosomal RNA 5LZZ_8 Chain 8, 5.8S ribosomal RNA 6P5I_8 Chain 8, 5.8S rRNA 6P5J_8 Chain 8, 5.8S rRNA 6P5K_8 Chain 8, 5.8S rRNA 6P5N_8 Chain 8, 5.8S rRNA 6R6P_8 Chain 8, 5.8S ribosomal RNA 6SGC_84 Chain 84, 5.8S ribosomal RNA 6T59_84 Chain 84, 5.8S ribosomal RNA 6Y0G_L8 Chain L8, 5.8S ribosomal RNA 6Y2L_L8 Chain L8, 5.8S ribosomal RNA 6Y57_L8 Chain L8, 5.8S ribosomal RNA 6ZVK_h2 Chain h2, 5.8S RIBOSOMAL RNA 6Y6X_L8 Chain L8, 5.8S ribosomal RNA 7NWI_8 Chain 8, 5.8S ribosomal RNA 7OBR_8 Chain 8, 5.8S ribosomal RNA 7MDZ_8 Chain 8, 5.8S rRNA 7QWR_8 Chain 8, 5.8S ribosomal RNA 7QWS_8 Chain 8, 5.8S rRNA 7QWQ_8 Chain 8, 5.8S ribosomal RNA 7TOQ_A58S Chain A58S, 5.8S rRNA 7TM3_v Chain v, 5.8S ribosomal RNA 7TUT_v Chain v, 5.8S ribosomal RNA 8B6C_8 Chain 8, 5.8S rRNA 8B5L_8 Chain 8, 5.8S rRNA 8BPO_C1 Chain C1, 5.8S ribosomal RNA 8BHF_C2 Chain C2, 5.8S ribosomal RNA 8BF9_8 Chain 8, RNA (156-MER) 8RJB_v Chain v, 5.8S rRNA 8RJC_v Chain v, 5.8S rRNA 8RJD_v Chain v, 5.8S rRNA      120     1.17e-53        100.000 100
A00984:21:HMKLFDMXX:2:2135:6325:12195|CB:Z:AAACAAGTATCTCCCA-1|UB:Z:ACTGTGTGTTAG N/A     AK397456.1 Sus scrofa mRNA, clone: SMG010018G10, expressed in submaxillary gland        99    2.57e-40 98.990  83
A00984:21:HMKLFDMXX:2:2135:6325:12226|CB:Z:AAACAAGTATCTCCCA-1|UB:Z:ACTGTGTGTTAG N/A     AK397456.1 Sus scrofa mRNA, clone: SMG010018G10, expressed in submaxillary gland        99    1.19e-38 97.980  83
A00984:21:HMKLFDMXX:1:1125:20627:2237|CB:Z:AAACAAGTATCTCCCA-1|UB:Z:AGAATGGAACAT N/A     AK397456.1 Sus scrofa mRNA, clone: SMG010018G10, expressed in submaxillary gland        102   5.51e-42 99.020  85
A00984:21:HMKLFDMXX:1:2151:17725:26678|CB:Z:AAACAAGTATCTCCCA-1|UB:Z:ATACTCACTGTA        N/A     AK009538.1 Mus musculus adult male tongue cDNA, RIKEN full-length enriched library, clone:2310030C18 product:unclassifiable, full insert sequence      120     1.17e-53        100.000 100
A00984:21:HMKLFDMXX:1:2466:13367:10614|CB:Z:AAACAAGTATCTCCCA-1|UB:Z:ATACTCACTGTA        N/A     AK009538.1 Mus musculus adult male tongue cDNA, RIKEN full-length enriched library, clone:2310030C18 product:unclassifiable, full insert sequence      120     1.17e-53        100.000 100
A00984:21:HMKLFDMXX:2:1260:15148:7153|CB:Z:AAACAAGTATCTCCCA-1|UB:Z:ATACTCACTGTA N/A     AK009538.1 Mus musculus adult male tongue cDNA, RIKEN full-length enriched library, clone:2310030C18 product:unclassifiable, full insert sequence      120     1.17e-53        100.000 100
A00984:21:HMKLFDMXX:1:2481:32253:13542|CB:Z:AAACAAGTATCTCCCA-1|UB:Z:ATTACGCACCGG        N/A     J02793.1 Mouse R and L1 (3' end) repetitive elements    120     1.17e-53        100.000100`


Sorry for late response.

**Comment by StackChan** [comment]
For the SI_SMT samples(ST2008PTPT01, provided by your paper), we can see there is microbe signals like Lactobacillus, Muribaculum, Duncaniella in its unmapped.nonpolyB.blast.tsv,

![image](https://github.com/user-attachments/assets/8b14a276-5e58-4981-a7aa-fbe47dbbcb08)


And for mouse kidney samples(fresh frozen Visium) in 10X website,
`https://www.10xgenomics.com/datasets/mouse-kidney-section-coronal-1-standard-1-1-0 and
https://www.10xgenomics.com/datasets/mouse-kidney-section-coronal-1-standard-1-0-0?`
I search their  unmapped.nonpolyB.blast.tsv and there is rarely microbe signals.

**Comment by StackChan** [comment]
And if possible, I sincerely ask for your email ,wechat, telegram or any other contacts to solve this tiny question as quick as we can and promote efficiency of both of us. Honestly I'm kind of tierd of such tough communication way.
Sincelely, Stack Chan
csk1657019234@qq.com
csk312191319@gmail.com

**Comment by StackChan** [comment]
Also, it's mentioned that "Then, standard ST procedures were carried out. For one of the windows, designated M1054B (patient
M1054, replicate window B), an additional 15-min lysozyme treatment was performed after the permeabilization step (Methods).
This step is commonly performed in FISH experiments and was
shown to increase capture of diverse species with cell walls
(Chassaing et al. 2014; Zou et al. 2018)" in your paper. And the mouse kidney may not be a tissue with particularly high bacterial content, especially when compared to Inflammatory Bowel Disease (IBD).

So does this explain why there are rarely microbes in `mouse kidney samples(fresh frozen Visium) in 10X website,
https://www.10xgenomics.com/datasets/mouse-kidney-section-coronal-1-standard-1-1-0 and https://www.10xgenomics.com/datasets/mouse-kidney-section-coronal-1-standard-1-0-0`?

**Comment by affinis** [comment]
add my wechat: 15274972986
And I think it is the problem of nt database

**Comment by StackChan** [comment]
I noticed the taxid in the unmapped.nonpolyB.blast.tsv is N/A. It's unnormal and I found that I lack the taxdb.tar.gz in my nt database as the [munual of blastn said.](https://www.ncbi.nlm.nih.gov/books/NBK569856/).

I should notice that in issue #2 the author give us a screenshot,
![image](https://github.com/user-attachments/assets/2ee41084-87bd-4900-87be-c8e16892f9cb)

There should be taxdb.ntb and taxdb.bti.
But I lack it. That because I simply run

`
ascp -i ~/.aspera/connect/etc/asperaweb_id_dsa.openssh -l 100M -k 1 -T anonftp@ftp.ncbi.nlm.nih.gov:/blast/db/FASTA/nt.gz ./
gunzip nt.gz

/data/pub/tools/ncbi-blast-2.15.0+/bin/makeblastdb -dbtype nucl -in /data/pub/songkang/nt/nt.fa -out /data/pub/songkang/nt/nt
...
├── nt.126.nhr
├── nt.126.nin
├── nt.126.nsq
├── nt.127.nhr
├── nt.127.nin
├── nt.127.nsq
├── nt.fa
...

`
I guess possibly '-parse_seqids' is also needed, and run as follows,
`/data/pub/tools/ncbi-blast-2.15.0+/bin/makeblastdb -dbtype nucl -parse_seqids -in /data/pub/songkang/nt/nt.fa -out /data/pub/songkang/nt/nt

wget -c "https://ftp.ncbi.nlm.nih.gov/blast/db/taxdb.tar.gz"
tar -xzvf taxdb.tar.gz
`

**Comment by affinis** [comment]
Yeah, that's the problem, In our expectation, users would download builded nt database (not simply download a fasta and using local blast command to build it) directly from the official site.
So if your way by building nt database with '-parse_seqids' not work, try to download a builded one.

**Comment by StackChan** [comment]
你好 我想问一下,blastn比对nt database时，一个query序列，会对应多个比对结果的。在one情况下，只看第一个比对结果，这个结果是什么物种，就定义query序列是什么物种。在all情况下，会对所有比对结果进行统计，做一个字典。这个query序列可以有多个物种相对应。
您只看一个结果,这样会不会很容易造成假阳性?
包括在 您给出的testdata数据中，有足足322个属，其中可能有很多都是假阳性的。在这方面，SAHMI采用kraken2，kraken2基于kmer且采用一套基于LCA，因此能够得出有多个物种相对应时最大概率的情况。（同时SAHMI也采集了一个实验室无菌环境下的微生物丰度数据作为背景，要大于99%百分位才会判定为真阳性。但是我复现中发现他这个数据库里采集的很多样本都没有说是无菌环境，因此很容易错判。）
想知道SMTa这样做会不会有问题？是不是采用kraken2会更好？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "affinis/SMTa"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月4日(星期三) 晚上9:12
***@***.***&gt;;
抄送:&nbsp;"Chen ***@***.******@***.***&gt;;
主题:&nbsp;Re: [affinis/SMTa] Run successful but generate nothing meaningful! (Issue #7)





 
add my wechat: 15274972986
 And I think it is the problem of nt database
